import { useState } from 'react';

const SECRET_KEY =
  'DFTR-ABU-ESLAM-2026';

  const cleanCode = (value: string) =>
    value
        .replace(/[^a-zA-Z0-9]/g, '')
            .toUpperCase();

            const formatDeviceCode = (value: string) =>
              cleanCode(value)
                  .slice(0, 24)
                      .match(/.{1,4}/g)
                          ?.join('-') || '';

                          const formatActivationCode = (value: string) =>
                            cleanCode(value)
                                .slice(0, 16)
                                    .match(/.{1,4}/g)
                                        ?.join('-') || '';

                                        async function createActivationCode(
                                          deviceCode: string
                                          ) {
                                            const formattedDevice =
                                                formatDeviceCode(deviceCode);

                                                  const text =
                                                      `${formattedDevice}-${SECRET_KEY}`;

                                                        const data =
                                                            new TextEncoder().encode(text);

                                                              const hash =
                                                                  await crypto.subtle.digest(
                                                                        'SHA-256',
                                                                              data
                                                                                  );

                                                                                    const bytes =
                                                                                        Array.from(new Uint8Array(hash));

                                                                                          const hex =
                                                                                              bytes
                                                                                                    .map((b) =>
                                                                                                            b.toString(16).padStart(2, '0')
                                                                                                                  )
                                                                                                                        .join('')
                                                                                                                              .toUpperCase();

                                                                                                                                return formatActivationCode(hex);
                                                                                                                                }

                                                                                                                                export default function AdminLicense() {
                                                                                                                                  const [deviceCode, setDeviceCode] =
                                                                                                                                      useState('');

                                                                                                                                        const [activationCode, setActivationCode] =
                                                                                                                                            useState('');

                                                                                                                                              const generateCode = async () => {
                                                                                                                                                  if (!deviceCode.trim()) {
                                                                                                                                                        alert('أدخل الرقم التسلسلي للجهاز');
                                                                                                                                                              return;
                                                                                                                                                                  }

                                                                                                                                                                      const code =
                                                                                                                                                                            await createActivationCode(deviceCode);

                                                                                                                                                                                setActivationCode(code);
                                                                                                                                                                                  };

                                                                                                                                                                                    const copyCode = async () => {
                                                                                                                                                                                        if (!activationCode) return;

                                                                                                                                                                                            await navigator.clipboard.writeText(
                                                                                                                                                                                                  activationCode
                                                                                                                                                                                                      );

                                                                                                                                                                                                          alert('تم نسخ كود التفعيل');
                                                                                                                                                                                                            };

                                                                                                                                                                                                              const copyMessage = async () => {
                                                                                                                                                                                                                  if (!activationCode) return;

                                                                                                                                                                                                                      const message =
                                                                                                                                                                                                                            `كود تفعيل تطبيق دفتر المقاول:\n\n` +
                                                                                                                                                                                                                                  `${activationCode}`;

                                                                                                                                                                                                                                      await navigator.clipboard.writeText(
                                                                                                                                                                                                                                            message
                                                                                                                                                                                                                                                );

                                                                                                                                                                                                                                                    alert('تم نسخ رسالة التفعيل');
                                                                                                                                                                                                                                                      };

                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                            <div className="activation-page">
                                                                                                                                                                                                                                                                  <div className="activation-card">
                                                                                                                                                                                                                                                                          <h1>🔑 مولد أكواد التفعيل</h1>

                                                                                                                                                                                                                                                                                  <p className="activation-note">
                                                                                                                                                                                                                                                                                            أدخل الرقم التسلسلي الذي أرسله لك
                                                                                                                                                                                                                                                                                                      المستخدم، ثم اضغط توليد الكود.
                                                                                                                                                                                                                                                                                                              </p>

                                                                                                                                                                                                                                                                                                                      <label className="field">
                                                                                                                                                                                                                                                                                                                                <span>الرقم التسلسلي للجهاز</span>

                                                                                                                                                                                                                                                                                                                                          <textarea
                                                                                                                                                                                                                                                                                                                                                      value={deviceCode}
                                                                                                                                                                                                                                                                                                                                                                  onChange={(e) =>
                                                                                                                                                                                                                                                                                                                                                                                setDeviceCode(
                                                                                                                                                                                                                                                                                                                                                                                                formatDeviceCode(e.target.value)
                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                                      rows={3}
                                                                                                                                                                                                                                                                                                                                                                                                                                                  placeholder="DFTR-XXXX-XXXX-XXXX-XXXX-XXXX"
                                                                                                                                                                                                                                                                                                                                                                                                                                                              dir="ltr"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="btn primary full"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={generateCode}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              توليد كود التفعيل
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {activationCode && (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <label
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  className="field"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                style={{ marginTop: 14 }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <span>كود التفعيل</span>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <input
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        value={activationCode}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        readOnly
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dir="ltr"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </label>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="row">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            className="btn gray"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            onClick={copyCode}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          نسخ الكود
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </button>

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <button
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      className="btn primary"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      onClick={copyMessage}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    نسخ الرسالة
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </button>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )}

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <p className="activation-small">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  هذه الصفحة خاصة بالمطور فقط، ولا يجب
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            إرسال هذه النسخة للمستخدمين.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }